[package]
name = "opcgw"
version = "0.2.5"
authors = ["Guy Corbaz <guy@corbaz.org>"]
description = "A Chirpstack to opc ua gateway"
readme = "README.md"
keywords = ["scada","gateway","opc_ua","chirpstack"]
license = "MIT OR Apache-2.0"
rust-version = "1.85.0"
edition = "2021"
categories = ["science"]
publish = false # for now, until a running version is available

[dependencies]
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full", "rt-multi-thread"] }
thiserror = "2.0.12"
log = "0.4.26"
log4rs = "1.3.0"
tonic = "0.12.3"
prost = "0.13.4"
tonic-build = "0.12.3"
chirpstack_api = "4.11.1"
prost-types = "0.13.5"
# opcua = "0.12.0"
opcua = {git = "https://github.com/locka99/opcua.git" }
clap = { version = "4.5.31", features = ["derive"] }
local-ip-address = "0.6.3"
ping = "0.5.2"
url = "2.5.4"

[build-dependencies]
tonic-build = "0.12.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
