[package]
name = "opc_ua_chirpstack_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.14.0", features = ["toml"] }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
