[package]
name = "opcgw"
version = "0.2.5"
authors = ["Guy Corbaz <guy@corbaz.org>"]
description = "A Chirpstack to opc ua gateway"
readme = "README.md"
keywords = ["scada","gateway","opc_ua","chirpstack"]
license = "MIT OR Apache-2.0"
rust-version = "1.85.0"
edition = "2021"
categories = ["science"]
publish = false # for now, until a running version is available

[dependencies]
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full", "rt-multi-thread"] }
thiserror = "2.0.12"
log = "0.4.27"
log4rs = "1.3.0"
tonic = "0.13.1"
tonic-build = "0.13.1"
chirpstack_api = "4.12.0"
prost-types = "0.13.5"
async-opcua = { version = "^0.15.1", features = ["server"] }
clap = { version = "4.5.40", features = ["derive"] }
local-ip-address = "0.6.5"
url = "2.5.4"

[build-dependencies]
tonic-build = "0.13.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
