[package]
name = "opc_ua_chirpstack_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.14.0", features = ["toml"] }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
thiserror = "1.0"
log = "0.4"
log4rs = "1.3"
tonic = "0.12"
prost = "0.13"
tonic-build = "0.12"
chirpstack_api = "4.9"
prost-types = "0.13.3"
opcua = "0.11"

[build-dependencies]
tonic-build = "0.12"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
