# Docker compose file for chirpstack opcua gateway

#version: '3.3'

services:
  opcgw:
    container_name: opcgw
    image: opcgw
    restart: always
    ports:
      - "4855:4855"
    volumes:
      - ./log:/usr/local/bin/log
      - ./config:/usr/local/bin/config
      - ./pki:/usr/local/bin/pki
