# Chirpstack server connection
[global]
debug = true


[chirpstack]

# Server address
#
# Example format
#   http://192.168.1.4:8080
#   http://xx.yy.com:8080
#
server_address = "http://192.168.1.12:8080"
# API token defined on the chirpstack server
api_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6ImY5MGIzNmM1LTNkMTAtNGY1YS05NTQ4LWZhNmFlMDllYzE5ZSIsInR5cCI6ImtleSJ9.j9sCvXaMhS1gzJBOhG0lYvN83NVTW6htQssHfQ79Mgo"
# Tenant Id that will be used
tenant_id = "52f14cd4-c6f1-4fbd-8f87-4025e1d49242"
# Frequency to poll ChirpStack server in seconds
polling_frequency = 20


# OPC UA parameters
[opcua]
config_file = "config/server.conf"





###########################################################
# Arrosage
###########################################################
[[application]]
application_id = "ae2012c2-75a1-407d-98ab-1520fb511edf"
application_name = "Arrosage"

    [[application.device]]
    device_name = "Niveau_citerne"
    device_id = "a840418371886840"

        [[application.device.metric]]
        metric_name ="Niveau"
        chirpstack_metric_name = "Water_deep_cm"

        [[application.device.metric]]
        metric_name ="Batterie"
        chirpstack_metric_name = "Bat_V"

    [[application.device]]
    device_name = "Vanne01"
    device_id = "524d1e0a02243201"

        [[application.device.metric]]
        metric_name ="Position"
        chirpstack_metric_name = "ValveStatus"

    [[application.device]]
    device_name = "Vanne02"
    device_id = "3f8e3904c1523201"

        [[application.device.metric]]
        metric_name ="Position"
        chirpstack_metric_name = "ValveStatus"

    [[application.device]]
    device_name = "Vanne03"
    device_id = "999b3d04c1523201"

        [[application.device.metric]]
        metric_name ="Position"
        chirpstack_metric_name = "ValveStatus"


###########################################################
# Bâtiments
###########################################################
[[application]]
application_id = "194f12ab-d0ab-4389-a446-f1b3e7152b07"
application_name ="Bâtiments"

    [[application.device]]
    device_name = "Magasin"
    device_id = "a840414bf185f365"

        [[application.device.metric]]
        metric_name ="Batterie"
        chirpstack_metric_name = "BatV"

        [[application.device.metric]]
        metric_name ="Humidité"
        chirpstack_metric_name = "Hum_SHT"

        [[application.device.metric]]
        metric_name ="Température"
        chirpstack_metric_name = "TempC_SHT"


    [[application.device]]
    device_name = "Grange"
    device_id = "a84041a44185f37d"

        [[application.device.metric]]
        metric_name ="Batterie"
        chirpstack_metric_name = "BatV"

        [[application.device.metric]]
        metric_name ="Humidité"
        chirpstack_metric_name = "Hum_SHT"

        [[application.device.metric]]
        metric_name ="Température"
        chirpstack_metric_name = "TempC_SHT"


###########################################################
# Cultures
###########################################################
[[application]]
application_id = "fca74250-823b-4dcb-adaf-fa8b99563533"
application_name = "Cultures"

    [[application.device]]
    device_name = "Verger2"
    device_id = "a8404159c1828ff0"

        [[application.device.metric]]
        metric_name ="Batterie"
        chirpstack_metric_name = "Batterie"

        [[application.device.metric]]
        metric_name ="Conductivité"
        chirpstack_metric_name = "Conductivité"

        [[application.device.metric]]
        metric_name ="Température"
        chirpstack_metric_name = "Température"

        [[application.device.metric]]
        metric_name ="Humidité"
        chirpstack_metric_name = "Humidité"


    [[application.device]]
    device_name = "Tunnel1"
    device_id = "a84041878185f36d"

        [[application.device.metric]]
        metric_name ="Batterie"
        chirpstack_metric_name = "BatV"

        [[application.device.metric]]
        metric_name ="Humidité"
        chirpstack_metric_name = "Hum_SHT"

        [[application.device.metric]]
        metric_name ="Température"
        chirpstack_metric_name = "TempC_SHT"


###########################################################
# Meteo
###########################################################
[[application]]
application_id = "81d88d98-81eb-48b3-8d0d-48c82361e187"
application_name = "Meteo"

    [[application.device]]
    device_name = "Station_meteo_01"
    device_id = "2cf7f1c06130048a"

        [[application.device.metric]]
        metric_name ="Température"
        chirpstack_metric_name = "Temp"

        [[application.device.metric]]
        metric_name ="Humidité"
        chirpstack_metric_name = "airHumidity"

        [[application.device.metric]]
        metric_name ="Pression"
        chirpstack_metric_name = "barometricPressure"

        [[application.device.metric]]
        metric_name ="Vitesse_vent"
        chirpstack_metric_name = "windSpeed"

        [[application.device.metric]]
        metric_name ="Direction_vent"
        chirpstack_metric_name = "windDirection"

        [[application.device.metric]]
        metric_name ="UVIndex"
        chirpstack_metric_name = "UVIndex"

        [[application.device.metric]]
        metric_name ="Intensité_lumineuse"
        chirpstack_metric_name = "lightIntensity"






