# Chirpstack server connection
[application]
debug = true


[chirpstack]

# Server address
#
# Example format
#   http://192.168.1.4:8080
#   http://xx.yy.com:8080
#
server_address = "http://192.168.1.12:8080"
# API token defined on the chirpstack server
api_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6ImY5MGIzNmM1LTNkMTAtNGY1YS05NTQ4LWZhNmFlMDllYzE5ZSIsInR5cCI6ImtleSJ9.j9sCvXaMhS1gzJBOhG0lYvN83NVTW6htQssHfQ79Mgo"
# Tenant Id that will be used
tenant_id = "52f14cd4-c6f1-4fbd-8f87-4025e1d49242"


# OPC UA parameters
[opcua]
# OPC UA server url
server_url = "opc.tcp://localhost:4840"
# OPC UA server name
server_name = "ChirpStack OPC UA Server"

# List of applications that have to be displayed in UPC UA
[applications]
arrosage = "ae2012c2-75a1-407d-98ab-1520fb511edf"
batiments = "194f12ab-d0ab-4389-a446-f1b3e7152b07"
cultures = "fca74250-823b-4dcb-adaf-fa8b99563533"
meteo = "81d88d98-81eb-48b3-8d0d-48c82361e187"


# Devices that have to be displayed in OPC UA
[devices]
niveau_citerne = "a840418371886840"
vanne01 = "524d1e0a02243201"
vanne02 = "3f8e3904c1523201"
vanne03 = "999b3d04c1523201"

