refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} - {l} - {t} - {m}{n}"
  opcua_log:
    kind: file
    path: "log/opc_ua.log"
    encoder:
      pattern: "{d} - {l} - {t} - {m}{n}"
  opcuagw_log:
    kind: file
    path: "log/opc_ua_gw.log"
    encoder:
      pattern: "{d} - {l} - {t} - {m}{n}"
  chirpstack_log:
    kind: file
    path: "log/chirpstack.log"
    encoder:
      pattern: "{d} - {l} - {t} - {m}{n}"
  storage_log:
    kind: file
    path: "log/storage.log"
    encoder:
      pattern: "{d} - {l} - {t} - {m}{n}"
  config_log:
    kind: file
    path: "log/config.log"
    encoder:
      pattern: "{d} - {l} - {t} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - opcuagw_log
loggers:
  opcgw::opc_ua:
    level: trace
    appenders:
      - opcua_log
  opcua_server:
    level: debug
    appenders:
      - opcua_log
  opcgw::chirpstack:
    level: trace
    appenders:
      - chirpstack_log
  opcgw::storage:
    level: trace
    appenders:
      - storage_log
  opcgw::config:
    level: trace
    appenders:
      - config_log
