#!/usr/bin/env bash
# build.sh — build the opcgw User Manual PDF (GH #145).
#
# LaTeX is the canonical manual format (DocBook retired 2026-06-27). The hand-
# maintained sources are main.tex + preamble.tex + body.tex. This script only:
#   1. converts the figure sources (SVG / Graphviz) to vector PDF,
#   2. stamps the version from Cargo.toml,
#   3. runs lualatex (via latexmk).
#
# Prereqs (Debian/Ubuntu): texlive-luatex, texlive-latex-extra, texlive-fonts-extra,
#   fonts-lato, fonts-noto, fonts-dejavu, graphviz (dot), mupdf-tools (mutool).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

IMG="../../images"
LOGO="../../logo"
FIG="figures"

echo "==> [1/3] Converting figure sources to vector PDF"
mkdir -p "$FIG"
# Architecture diagram: straight from Graphviz source for best quality.
if [[ -f "$IMG/architecture.dot" ]]; then
  dot -Tpdf "$IMG/architecture.dot" -o "$FIG/architecture.pdf"
else
  mutool convert -O resolution=300 -o "$FIG/architecture.pdf" "$IMG/architecture.svg"
fi
for svg in "$IMG"/screenshot-*.svg; do
  [[ -e "$svg" ]] || continue
  mutool convert -o "$FIG/$(basename "$svg" .svg).pdf" "$svg"
done
mutool convert -o "$FIG/opcgw-horizontal.pdf" "$LOGO/opcgw-horizontal.svg"

echo "==> [2/3] Writing version.tex from Cargo.toml"
VERSION="$(grep -m1 '^version' ../../../Cargo.toml | sed -E 's/.*"([^"]+)".*/\1/')"
printf '%% generated by build.sh — do not edit\n\\newcommand{\\opcgwversion}{%s}\n' "${VERSION:-dev}" > version.tex

echo "==> [3/3] lualatex (latexmk, multi-pass for refs/toc)"
latexmk -lualatex -interaction=nonstopmode -halt-on-error main.tex >/dev/null

cp main.pdf opcgw-user-manual.pdf
echo "==> DONE: $HERE/opcgw-user-manual.pdf"
