title: opcgw
tagline: Bridge LoRaWAN to Industrial Systems
description: Open-source ChirpStack to OPC UA Gateway
url: "https://guycorbaz.github.io/opcgw"
baseurl: "/opcgw"

theme: null
remote_theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Guy Corbaz
  email: gcorbaz@gmail.com
  github: guycorbaz

markdown: kramdown
highlighter: rouge
