name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          #- stable
          #- beta
          - nightly
    steps:
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler-grpc
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - run: cargo build --verbose
      - run: cargo test --verbose