
name: Publish Docker image

on: workflow_dispatch
  # release:
  #  types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler-grpc
      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: actions/checkout@v4
      - name: Build application
        run: cargo build --verbose --release
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest