
name: Build and push image to DockerHub

# Event
on:
  push:
    #branches:
    #  - 'master'
    tags:
      - 'v*'

jobs:
  build_docker_images:
    name: Build Docker Image to Dockerhub
    runs-on: [ubuntu-latest]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: gcorbaz/opcgw

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
